name: instagram_clone
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  api_repository:
    path: packages/api_repository
  bloc: ^8.1.4
  env:
    path: packages/env
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  supabase_flutter: ^2.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
