// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUWwt9WB1qJbd93sIWfX03tfgVec_LEw',
    appId: '1:33103462281:web:38ca2fd92fbf7cff0feb58',
    messagingSenderId: '33103462281',
    projectId: 'instagramclone-dev-9a2b5',
    authDomain: 'instagramclone-dev-9a2b5.firebaseapp.com',
    storageBucket: 'instagramclone-dev-9a2b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsbeKbFjPK3b7bUQGL4tJTa4OZpl9IIfc',
    appId: '1:33103462281:android:997652f93a4ff6640feb58',
    messagingSenderId: '33103462281',
    projectId: 'instagramclone-dev-9a2b5',
    storageBucket: 'instagramclone-dev-9a2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZfIYYhq_c5st_RXKW_6nzHBncwFUc4g',
    appId: '1:33103462281:ios:c0cfcd135c2342490feb58',
    messagingSenderId: '33103462281',
    projectId: 'instagramclone-dev-9a2b5',
    storageBucket: 'instagramclone-dev-9a2b5.appspot.com',
    iosClientId: '33103462281-v5h15vsh3f48t69usb80hkhtqe12io5h.apps.googleusercontent.com',
    iosBundleId: 'com.luizsohapps.instagramClone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZfIYYhq_c5st_RXKW_6nzHBncwFUc4g',
    appId: '1:33103462281:ios:c0cfcd135c2342490feb58',
    messagingSenderId: '33103462281',
    projectId: 'instagramclone-dev-9a2b5',
    storageBucket: 'instagramclone-dev-9a2b5.appspot.com',
    iosClientId: '33103462281-v5h15vsh3f48t69usb80hkhtqe12io5h.apps.googleusercontent.com',
    iosBundleId: 'com.luizsohapps.instagramClone.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUWwt9WB1qJbd93sIWfX03tfgVec_LEw',
    appId: '1:33103462281:web:d5b5bb244ff3d5d90feb58',
    messagingSenderId: '33103462281',
    projectId: 'instagramclone-dev-9a2b5',
    authDomain: 'instagramclone-dev-9a2b5.firebaseapp.com',
    storageBucket: 'instagramclone-dev-9a2b5.appspot.com',
  );
}
