// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarEzq9Ho2Uda-oFLY8mvJWT5aOj3jnNM',
    appId: '1:73840811636:web:ca2cfb449a6bf5a5d5fb21',
    messagingSenderId: '73840811636',
    projectId: 'instagramclone-staging',
    authDomain: 'instagramclone-staging.firebaseapp.com',
    storageBucket: 'instagramclone-staging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAErzDNDWJzI1pR2hAWANgDT9PEElY2ZzQ',
    appId: '1:73840811636:android:4dd0b29ec2170e5dd5fb21',
    messagingSenderId: '73840811636',
    projectId: 'instagramclone-staging',
    storageBucket: 'instagramclone-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndIxldW_TMyb7g-1qB4EPP7tHIlLWXz0',
    appId: '1:73840811636:ios:5ff3fb3c73a1cd22d5fb21',
    messagingSenderId: '73840811636',
    projectId: 'instagramclone-staging',
    storageBucket: 'instagramclone-staging.appspot.com',
    iosClientId: '73840811636-t990gfkh3qb0g4na1oip9pjgtu19a31d.apps.googleusercontent.com',
    iosBundleId: 'com.luizsohapps.instagramClone.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndIxldW_TMyb7g-1qB4EPP7tHIlLWXz0',
    appId: '1:73840811636:ios:5ff3fb3c73a1cd22d5fb21',
    messagingSenderId: '73840811636',
    projectId: 'instagramclone-staging',
    storageBucket: 'instagramclone-staging.appspot.com',
    iosClientId: '73840811636-t990gfkh3qb0g4na1oip9pjgtu19a31d.apps.googleusercontent.com',
    iosBundleId: 'com.luizsohapps.instagramClone.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAarEzq9Ho2Uda-oFLY8mvJWT5aOj3jnNM',
    appId: '1:73840811636:web:1ca48b6ad2289e54d5fb21',
    messagingSenderId: '73840811636',
    projectId: 'instagramclone-staging',
    authDomain: 'instagramclone-staging.firebaseapp.com',
    storageBucket: 'instagramclone-staging.appspot.com',
  );
}
